### ISSUE TITLE
Installing package from npm doesn't work

### ISSUE THREAD

**Issue by waringr** [lesimoes/sqs-huge-message#1]
When I install the package from npm, I get an error because the `main` is set incorrectly in the `package.json`. It's currently `index.js` when it should be `src/sqs-huge-msg.ts`. Please see image below. 
![initial-error](https://user-images.githubusercontent.com/79579024/117415701-832c7b00-af10-11eb-8f58-01eec5eee961.png)

I've got a Pull Request incoming to fix this, but I wanted an issue number to link it to, hence the ticket. I'll link to the PR from here once I've submitted it.

**Comment by waringr** [comment]
Please see PR https://github.com/lesimoes/sqs-huge-message/pull/2 for fix.

Thanks

Rob

**Comment by lesimoes** [comment]
Thanks for share your solution.
Have a greate week
